services:
  jekyll-site:
    image: jekyll-site
    build: .
    volumes: [ .:/usr/src/app ]
    ports: [ 4000:4000, 35729:35729 ]
    user: 1000:1000
    environment: [ JEKYLL_ENV=docker ]
    command: bundle exec jekyll serve -H 0.0.0.0 -P 4000 -w -l --force_polling --config _config.yml,_config_docker.yml
